name: Run The Dadra And Nagar Haveli And Daman And Diu pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    uses: ./.github/workflows/run-state-pipeline.yml
    with:
      state_code: "38"
      state_name: "The Dadra And Nagar Haveli And Daman And Diu"
