name: Run Meghalaya pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    uses: ./.github/workflows/run-state-pipeline.yml
    with:
      state_code: "17"
      state_name: "Meghalaya"
