name: Run Mizoram pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    uses: ./.github/workflows/run-state-pipeline.yml
    with:
      state_code: "15"
      state_name: "Mizoram"
