name: Run Lakshadweep pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    uses: ./.github/workflows/run-state-pipeline.yml
    with:
      state_code: "31"
      state_name: "Lakshadweep"
